### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by chycken** [ghostcap-gaming/ACMRS-cs2-metamod-update-fix#1]
Hello, its not working on my server. It doesnt do anything, and after every cs2 update, cs2.sh file changes to default

**Comment by pedrotski** [comment]
You will need to contact your host about that, unfortunately.

**Comment by chycken** [comment]
Tested on another host, still not working.

**Comment by pedrotski** [comment]
> Tested on another host, still not working.

It's not possible unless you have not put the file in the correct location or have missed a step. If you're 100% sure that's all correct, then make sure you're not using something like WinSCP to upload the file to your server, as sometimes that breaks the encoding of a file. Use Filezilla or create the file manually on your server.
